# Generated by Django 4.2.0 on 2025-09-04 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=100)),
                ('medical_record_id', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

