// services/vaccinationAutoScheduler.js
import { doc, setDoc, collection, query, where, getDocs, orderBy, limit, updateDoc } from 'firebase/firestore'
import { db } from '@shared/firebase'
import { generateVaccinationAppointments, updatePetVaccinationProgress } from './vaccinationSeriesService'

/**
 * Automatically schedule next vaccination appointments for a pet
 * @param {Object} pet - Pet object
 * @param {Array} existingVaccinations - Array of existing vaccination records
 * @param {Object} user - User object (owner)
 * @returns {Promise<Array>} Array of created appointment suggestions
 */
export async function autoScheduleVaccinations(pet, existingVaccinations = [], user = null) {
  try {
    console.log('🔄 Starting auto-scheduling for pet:', pet.name, 'with data:', {
      species: pet.species,
      birthDate: pet.birthDate,
      ageWeeks: pet.ageWeeks,
      ageMonths: pet.ageMonths,
      ageYears: pet.ageYears
    })
    
    // Generate vaccination appointment suggestions
    const appointmentSuggestions = generateVaccinationAppointments(pet, existingVaccinations)
    console.log('📅 Generated appointment suggestions:', appointmentSuggestions.length, appointmentSuggestions)
    
    if (appointmentSuggestions.length === 0) {
      console.log(`No vaccination appointments needed for ${pet.name}`)
      return []
    }
    
    // Find available vaccination services
    const availableServices = await findVaccinationServices()
    console.log('🔍 Found available vaccination services:', availableServices.length, availableServices.map(s => s.name))
    
    // Create appointment suggestions with service mapping
    const scheduledAppointments = []
    
    for (const suggestion of appointmentSuggestions) {
      // Find matching service
      const matchingService = findMatchingService(suggestion.serviceName, availableServices)
      console.log(`🔍 Looking for service matching "${suggestion.serviceName}":`, matchingService ? matchingService.name : 'No match')
      
      if (matchingService) {
        const appointmentData = {
          id: `vacc_suggest_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          type: 'vaccination_suggestion',
          status: 'suggestion',
          petId: pet.id,
          petName: pet.name,
          serviceId: matchingService.id,
          serviceName: matchingService.name,
          suggestedDate: suggestion.suggestedDate,
          priority: suggestion.priority,
          series: suggestion.series,
          dose: suggestion.dose,
          totalDoses: suggestion.totalDoses,
          isCore: suggestion.isCore,
          description: suggestion.description,
          estimatedDuration: suggestion.estimatedDuration,
          notes: suggestion.notes,
          createdAt: new Date(),
          updatedAt: new Date(),
          isAutoGenerated: true,
          source: 'vaccination_series'
        }
        
        // Save to Firestore
        await saveVaccinationSuggestion(appointmentData)
        scheduledAppointments.push(appointmentData)
        
        console.log(`✅ Created vaccination suggestion for ${pet.name}: ${suggestion.serviceName}`)
      } else {
        console.log(`❌ No matching service found for ${suggestion.serviceName}`)
      }
    }
    
    console.log(`🎯 Auto-scheduling completed for ${pet.name}: ${scheduledAppointments.length} suggestions created`)
    return scheduledAppointments
  } catch (error) {
    console.error('Error auto-scheduling vaccinations:', error)
    throw new Error('Failed to auto-schedule vaccinations')
  }
}

/**
 * Find available vaccination services in the system
 * @returns {Promise<Array>} Array of vaccination services
 */
async function findVaccinationServices() {
  try {
    const servicesRef = collection(db, 'services')
    const q = query(
      servicesRef,
      where('isVaccination', '==', true),
      where('archived', '==', false)
    )
    
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error('Error finding vaccination services:', error)
    return []
  }
}

/**
 * Find the best matching service for a vaccination suggestion
 * @param {string} vaccineName - Name of the vaccine
 * @param {Array} availableServices - Array of available services
 * @returns {Object|null} Matching service or null
 */
function findMatchingService(vaccineName, availableServices) {
  if (!availableServices || availableServices.length === 0) {
    return null
  }
  
  const vaccineNameLower = vaccineName.toLowerCase()
  
  // Try exact match first
  let exactMatch = availableServices.find(service => 
    service.name.toLowerCase() === vaccineNameLower
  )
  
  if (exactMatch) return exactMatch
  
  // Try partial matches
  const partialMatches = availableServices.filter(service => {
    const serviceNameLower = service.name.toLowerCase()
    
    // Check if service name contains key vaccine terms
    const keyTerms = vaccineNameLower.split(' ')
    return keyTerms.some(term => 
      term.length > 2 && serviceNameLower.includes(term)
    )
  })
  
  if (partialMatches.length > 0) {
    // Return the best partial match (prioritize core vaccines)
    return partialMatches.sort((a, b) => {
      if (a.name.toLowerCase().includes('core') && !b.name.toLowerCase().includes('core')) return -1
      if (!a.name.toLowerCase().includes('core') && b.name.toLowerCase().includes('core')) return 1
      return 0
    })[0]
  }
  
  // Fallback to generic vaccination service
  return availableServices.find(service => 
    service.name.toLowerCase().includes('vaccination') ||
    service.name.toLowerCase().includes('vaccine')
  ) || availableServices[0]
}

/**
 * Save vaccination suggestion to Firestore
 * @param {Object} appointmentData - Appointment suggestion data
 * @returns {Promise} Save result
 */
async function saveVaccinationSuggestion(appointmentData) {
  try {
    const suggestionRef = doc(db, 'vaccinationSuggestions', appointmentData.id)
    await setDoc(suggestionRef, appointmentData)
    return { success: true, id: appointmentData.id }
  } catch (error) {
    console.error('Error saving vaccination suggestion:', error)
    throw new Error('Failed to save vaccination suggestion')
  }
}

/**
 * Get all vaccination suggestions for a pet
 * @param {string} petId - Pet ID
 * @returns {Promise<Array>} Array of vaccination suggestions
 */
export async function getVaccinationSuggestions(petId) {
  try {
    const suggestionsRef = collection(db, 'vaccinationSuggestions')
    const q = query(
      suggestionsRef,
      where('petId', '==', petId),
      where('status', '==', 'suggestion'),
      orderBy('suggestedDate', 'asc')
    )
    
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error('Error fetching vaccination suggestions:', error)
    return []
  }
}

/**
 * Get all vaccination suggestions for a user
 * @param {string} userId - User ID
 * @returns {Promise<Array>} Array of vaccination suggestions
 */
export async function getUserVaccinationSuggestions(userId) {
  try {
    // First get user's pets
    const petsRef = collection(db, 'pets')
    const petsQuery = query(petsRef, where('userId', '==', userId))
    const petsSnapshot = await getDocs(petsQuery)
    
    if (petsSnapshot.empty) return []
    
    const petIds = petsSnapshot.docs.map(doc => doc.id)
    
    // Get suggestions for all user's pets
    const suggestionsRef = collection(db, 'vaccinationSuggestions')
    const suggestionsQuery = query(
      suggestionsRef,
      where('petId', 'in', petIds),
      where('status', '==', 'suggestion'),
      orderBy('suggestedDate', 'asc')
    )
    
    const suggestionsSnapshot = await getDocs(suggestionsQuery)
    return suggestionsSnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error('Error fetching user vaccination suggestions:', error)
    return []
  }
}

/**
 * Convert vaccination suggestion to actual appointment
 * @param {string} suggestionId - Vaccination suggestion ID
 * @param {Object} appointmentData - Additional appointment data
 * @returns {Promise<Object>} Created appointment
 */
export async function convertSuggestionToAppointment(suggestionId, appointmentData = {}) {
  try {
    // Get the suggestion
    const suggestionsRef = collection(db, 'vaccinationSuggestions')
    const suggestionDoc = await getDocs(query(suggestionsRef, where('id', '==', suggestionId)))
    
    if (suggestionDoc.empty) {
      throw new Error('Vaccination suggestion not found')
    }
    
    const suggestion = suggestionDoc.docs[0].data()
    
    // Create appointment data
    const newAppointment = {
      services: [suggestion.serviceId],
      serviceNames: [suggestion.serviceName],
      duration: suggestion.estimatedDuration || 30,
      petIds: [suggestion.petId],
      petNames: [suggestion.petName],
      doctorId: appointmentData.doctorId || null,
      doctorName: appointmentData.doctorName || null,
      date: appointmentData.date || suggestion.suggestedDate,
      time: appointmentData.time || null,
      userId: appointmentData.userId || suggestion.userId,
      status: appointmentData.status || 'pending',
      isVaccination: true,
      vaccinationSeries: suggestion.series,
      vaccinationDose: suggestion.dose,
      vaccinationTotalDoses: suggestion.totalDoses,
      isCore: suggestion.isCore,
      notes: suggestion.notes,
      createdAt: new Date(),
      updatedAt: new Date(),
      source: 'vaccination_auto_schedule',
      originalSuggestionId: suggestionId,
      // Add auto-approval metadata if provided
      ...(appointmentData.isAutoApproved && {
        isAutoApproved: appointmentData.isAutoApproved,
        autoApprovedAt: appointmentData.autoApprovedAt,
        autoApprovedReason: appointmentData.autoApprovedReason
      })
    }
    
    // Save to appointments collection
    const appointmentRef = doc(collection(db, 'appointments'))
    await setDoc(appointmentRef, {
      ...newAppointment,
      id: appointmentRef.id
    })
    
    // Update suggestion status
    await updateVaccinationSuggestionStatus(suggestionId, 'converted')
    
    return { ...newAppointment, id: appointmentRef.id }
  } catch (error) {
    console.error('Error converting suggestion to appointment:', error)
    throw new Error('Failed to convert suggestion to appointment')
  }
}

/**
 * Update vaccination suggestion status
 * @param {string} suggestionId - Suggestion ID
 * @param {string} status - New status
 * @returns {Promise} Update result
 */
async function updateVaccinationSuggestionStatus(suggestionId, status) {
  try {
    const suggestionRef = doc(db, 'vaccinationSuggestions', suggestionId)
    await updateDoc(suggestionRef, {
      status: status,
      updatedAt: new Date()
    })
    return { success: true }
  } catch (error) {
    console.error('Error updating vaccination suggestion status:', error)
    throw new Error('Failed to update suggestion status')
  }
}

/**
 * Process completed vaccination and auto-schedule next dose
 * @param {Object} completedVaccination - Completed vaccination record
 * @param {Object} pet - Pet object
 * @param {Object} user - User object
 * @returns {Promise<Array>} Array of new appointment suggestions
 */
export async function processCompletedVaccination(completedVaccination, pet, user) {
  try {
    console.log('🩺 Processing completed vaccination for autoscheduling...', { 
      pet: pet.name, 
      vaccine: completedVaccination.name,
      petData: {
        id: pet.id,
        species: pet.species,
        birthDate: pet.birthDate,
        ageWeeks: pet.ageWeeks,
        ageMonths: pet.ageMonths,
        ageYears: pet.ageYears
      }
    })
    
    // Update pet's vaccination progress
    await updatePetVaccinationProgress(pet.id, completedVaccination)
    console.log('✅ Updated pet vaccination progress')
    
    // Auto-schedule next vaccinations
    const newSuggestions = await autoScheduleVaccinations(pet, [completedVaccination], user)
    console.log('✅ Generated vaccination suggestions:', newSuggestions.length)
    console.log('📋 Suggestions details:', newSuggestions)
    
    // Convert suggestions to actual appointments with auto-approved status
    const createdAppointments = []
    for (const suggestion of newSuggestions) {
      try {
        const appointment = await convertSuggestionToAppointment(suggestion.id, {
          userId: user?.id || user?.userId,
          status: 'approved', // Auto-approved status as requested
          isAutoApproved: true,
          autoApprovedAt: new Date(),
          autoApprovedReason: 'Vaccination series continuation'
        })
        createdAppointments.push(appointment)
        console.log('✅ Created auto-approved appointment:', appointment.id)
      } catch (error) {
        console.error('❌ Failed to create appointment from suggestion:', error)
      }
    }
    
    console.log(`🎯 Processed completed vaccination for ${pet.name}, created ${createdAppointments.length} auto-approved appointments`)
    
    return createdAppointments
  } catch (error) {
    console.error('Error processing completed vaccination:', error)
    throw new Error('Failed to process completed vaccination')
  }
}

/**
 * Get overdue vaccinations for a pet
 * @param {Object} pet - Pet object
 * @param {Array} existingVaccinations - Array of existing vaccination records
 * @returns {Array} Array of overdue vaccinations
 */
export function getOverdueVaccinations(pet, existingVaccinations = []) {
  const upcomingVaccinations = generateVaccinationAppointments(pet, existingVaccinations)
  const now = new Date()
  
  return upcomingVaccinations.filter(vaccination => {
    const dueDate = new Date(vaccination.suggestedDate)
    return dueDate < now
  })
}

/**
 * Get vaccination schedule summary for a pet
 * @param {Object} pet - Pet object
 * @param {Array} existingVaccinations - Array of existing vaccination records
 * @returns {Object} Vaccination schedule summary
 */
export function getVaccinationScheduleSummary(pet, existingVaccinations = []) {
  const upcomingVaccinations = generateVaccinationAppointments(pet, existingVaccinations)
  const overdueVaccinations = getOverdueVaccinations(pet, existingVaccinations)
  
  const completedVaccinations = existingVaccinations.filter(v => v.completed)
  const pendingVaccinations = upcomingVaccinations.filter(v => !v.completed)
  
  return {
    total: existingVaccinations.length + upcomingVaccinations.length,
    completed: completedVaccinations.length,
    pending: pendingVaccinations.length,
    overdue: overdueVaccinations.length,
    nextDue: upcomingVaccinations.length > 0 ? upcomingVaccinations[0] : null,
    series: upcomingVaccinations.length > 0 ? upcomingVaccinations[0].series : null,
    progress: existingVaccinations.length > 0 ? 
      Math.round((completedVaccinations.length / existingVaccinations.length) * 100) : 0
  }
}
