<template>
  <div class="flex flex-col lg:flex-row min-h-full gap-8">
    <!-- Navigation Sidebar -->
    <nav class="lg:w-64 flex-shrink-0">
      <div class="lg:sticky lg:top-4 bg-white rounded-lg p-4 shadow-sm">
        <h2 class="text-lg font-semibold text-gray-900 mb-4">Table of Contents</h2>
        <ul class="space-y-2">
          <li v-for="(section, index) in sections" :key="index">
            <a
              :href="`#section-${index + 1}`"
              class="flex items-center space-x-3 px-3 py-2 rounded-lg transition-colors duration-200"
              :class="[
                activeSection === `section-${index + 1}`
                  ? 'bg-blue-50 text-blue-600'
                  : 'hover:bg-gray-50 text-gray-600 hover:text-gray-900'
              ]"
              @click="scrollToSection(`section-${index + 1}`)"
            >
              <span class="flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-full bg-blue-100 text-blue-600 text-sm font-medium">
                {{ index + 1 }}
              </span>
              <span class="text-sm font-medium">{{ section }}</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Main Content -->
    <div class="flex-grow max-w-3xl">
      <h1 class="text-2xl font-bold text-gray-900 mb-6">ProVet Terms and Conditions</h1>

      <!-- Section 1: Introduction -->
      <section id="section-1" class="mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">1. Introduction</h2>
        <p class="text-gray-600 leading-relaxed">
          Welcome to ProVet, an advanced Pet Health Management System designed to enhance veterinary services through telehealth, health risk prediction, and chatbot support. This agreement outlines the terms and conditions governing the use of ProVet by Administrators ("Admins"), Veterinarians ("Veterinarians"), and Pet Owners ("Users"). By accessing and using ProVet, you accept and agree to comply with these terms. If you do not agree, please refrain from using the system.
        </p>
      </section>

      <!-- Section 2: Definitions -->
      <section id="section-2" class="mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">2. Definitions</h2>
        <p class="text-gray-600 leading-relaxed">
          ProVet refers to the pet health management system, encompassing all functionalities provided on both web and mobile platforms. An Admin is a designated individual responsible for overseeing ProVet's operational aspects, including data management and user administration. A Veterinarian is a certified professional registered on ProVet to provide telehealth consultations, risk assessments, and related veterinary care. A Pet Owner is an individual who utilizes ProVet for managing their pet's health records, accessing veterinary services, and interacting with the platform.
        </p>
      </section>

      <!-- Remaining sections -->
      <section v-for="i in 12" :key="i + 2" :id="`section-${i + 2}`" class="mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">{{ i + 2 }}. {{ sections[i + 2] }}</h2>
        <p class="text-gray-600 leading-relaxed">
          {{ content[i + 2] }}
        </p>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';

const sections = [
  'Introduction',
  'Definitions',
  'Scope of Services',
  'User Responsibilities',
  'Payment and Fees',
  'Privacy and Data Protection',
  'Intellectual Property',
  'Limitations of Liability',
  'Third-Party Services and Links',
  'Termination and Suspension',
  'Modifications to Terms',
  'Governing Law and Dispute Resolution',
  'Contact Information'
];

const content = {
  3: 'To register and use ProVet, a user must be at least 18 years old. Veterinarians are required to submit proof of licensure and accreditation before being authorized to provide services. Users must provide accurate registration details and are responsible for keeping their account credentials secure.',
  4: 'ProVet serves as a platform for facilitating communication between pet owners and veterinarians but does not replace in-person veterinary consultations when required. Health risk predictions generated by ProVet system are intended for informational purposes only.',
  5: 'All users are required to comply with applicable laws and regulations while using ProVet. Pet owners must ensure that they provide complete and accurate pet health information to receive appropriate recommendations.',
  6: 'Some ProVet features may require payment, and users will be notified of applicable fees before engaging with paid services. Payments are processed through external third-party providers, and ProVet does not store payment details.',
  7: 'ProVet collects and processes user data, including personal and pet health information, in accordance with its Privacy Policy. By using ProVet, users consent to the collection, storage, and processing of their data.',
  8: 'ProVet, including all associated trademarks, logos, and software, is the intellectual property of ProVet and its licensors. Users are prohibited from reproducing, distributing, or modifying any part of ProVet without prior written consent.',
  9: 'ProVet is not liable for any direct, indirect, incidental, or consequential damages arising from the use or inability to use the platform. Veterinarians remain independently responsible for the professional services they provide through ProVet.',
  10: 'ProVet may include links or integrations with external third-party services. ProVet does not endorse or assume responsibility for the accuracy, security, or content of third-party services.',
  11: 'ProVet reserves the right to suspend or terminate any user account that is found to be in violation of these terms and conditions. Users may request account deletion at any time.',
  12: 'ProVet retains the right to update these terms and conditions at its sole discretion. Continued use of the platform after any modifications constitutes acceptance of the revised terms.',
  13: 'These terms shall be governed by and interpreted in accordance with the laws of the applicable jurisdiction. Any disputes arising from the use of ProVet shall be resolved through arbitration.',
  14: 'For any questions or concerns regarding these terms and conditions, users may contact ProVet support through our help center or email support@provet.com.'
};

const activeSection = ref('section-1');

const scrollToSection = (sectionId) => {
  const element = document.getElementById(sectionId);
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' });
  }
};

const handleScroll = () => {
  const sections = document.querySelectorAll('section');
  sections.forEach((section) => {
    const rect = section.getBoundingClientRect();
    if (rect.top >= 0 && rect.top <= window.innerHeight / 2) {
      activeSection.value = section.id;
    }
  });
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll, { passive: true });
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});
</script>

<style scoped>
/* Smooth scrolling behavior for the entire component */
html {
  scroll-behavior: smooth;
}

/* Hide scrollbar for Chrome, Safari and Opera */
.hide-scrollbar::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.hide-scrollbar {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
</style>